image: hashicorp/terraform:1.1.4

pipelines:
  default:
    - parallel:
      - step:
          name: 'Init and plan'
          script:
            - git clone git@bitbucket.org:warnerb47/configuration.git
            - cp configuration/aws/aws-security-config.yml ./aws/config.yml
            - cd aws
            - terraform init
            - terraform plan
      - step:
          name: 'Test'
          script:
            - echo "Test ..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Apply changes'
        deployment: production
        trigger: 'manual'
        script:
          - git clone git@bitbucket.org:warnerb47/configuration.git
          - cp configuration/aws/aws-security-config.yml ./aws/config.yml
          - cd aws
          - terraform init
          - terraform plan
          - terraform apply -auto-approve
    - step:
        name: 'Trigger vm-tfm-module pipeline'
        script:
          - echo "now trigger vm-tfm-module pipeline" 
